import fs from "node:fs";
import path from "node:path";
import { WIKI_ANSWERS_DIR, WIKI_ANSWERS_INDEX_PATH } from "../../lib/paths.js";
import type { SourceInfo, Strategy } from "../../lib/types.js";
import { slugify } from "./parser.js";

export interface FiledAnswerInput {
  query: string;
  answer: string;
  sources: SourceInfo[];
  strategy: Strategy;
  filedAt: string;
}

interface AnswerIndexEntry {
  slug: string;
  question: string;
  strategy: string;
  filed_at: string;
}

// A bare inline citation as emitted by the LLM, e.g. [refund_policy.md#refund-timeline].
// Not preceded by `]` and not followed by `(` so we never touch an existing markdown link.
const CITATION_RE = /(?<!\])\[([a-z0-9_-]+\.md#[a-z0-9-]+)\](?!\()/gi;

/** Filename-safe slug for a question; falls back to "answer" when empty. */
export function answerSlug(query: string): string {
  // slugify() would return its generic "section" fallback for a query with no
  // slug-able characters; "answer" reads better for a filed Q&A.
  if (!/[a-z0-9]/i.test(query)) return "answer";
  return slugify(query);
}

/** Split a `<file>#<slug>` source id into its file and anchor parts. */
function splitSource(source: string): { file: string; anchor: string } {
  const hash = source.indexOf("#");
  if (hash === -1) return { file: source, anchor: "" };
  return { file: source.slice(0, hash), anchor: source.slice(hash + 1) };
}

/**
 * Render a filed answer as Markdown for `wiki/answers/<slug>.md`.
 *
 * Preserves grounding two ways: inline `[file.md#slug]` citations in the answer body are
 * rewritten into links back to the source section, and every retrieved source is listed
 * under "## Sources" with its score. Links are relative to `wiki/answers/`, hence `../../docs`.
 *
 * Pure — no filesystem access — so it is unit-testable.
 */
export function renderFiledAnswer(input: FiledAnswerInput): string {
  const { query, answer, sources, strategy, filedAt } = input;

  const frontMatter = [
    "---",
    `question: ${JSON.stringify(query)}`,
    `strategy: ${strategy}`,
    `filed_at: ${filedAt}`,
    `slug: ${answerSlug(query)}`,
    "---",
  ].join("\n");

  const linkedAnswer = answer.replace(CITATION_RE, (_m, id: string) => `[${id}](../../docs/${id})`);

  const sourceLines =
    sources.length === 0
      ? ["_No sources cited._"]
      : sources.map((s) => {
          const { file, anchor } = splitSource(s.source);
          return `- [${s.heading}](../../docs/${file}#${anchor}) — score ${s.score}`;
        });

  return [
    frontMatter,
    "",
    `# ${query}`,
    "",
    linkedAnswer.trim(),
    "",
    "## Sources",
    "",
    sourceLines.join("\n"),
    "",
  ].join("\n");
}

/** Render `wiki/answers/index.md` listing every filed answer, newest first. */
export function renderAnswersIndex(entries: AnswerIndexEntry[]): string {
  const header = [
    "# Filed Answers",
    "",
    "<!-- Generated by POST /file-answer. Do not edit by hand. -->",
    "",
    `**${entries.length} ${entries.length === 1 ? "answer" : "answers"}**`,
  ];

  if (entries.length === 0) {
    return [...header, "", "_No answers filed yet._", ""].join("\n");
  }

  const sorted = [...entries].sort((a, b) => b.filed_at.localeCompare(a.filed_at));
  const lines = sorted.map((e) => {
    const date = e.filed_at.slice(0, 10);
    return `- [${e.question}](${e.slug}.md) — ${e.strategy}, filed ${date}`;
  });

  return [...header, "", lines.join("\n"), ""].join("\n");
}

/** Read a filed answer file's front matter back into an index entry. */
function parseAnswerFrontMatter(slug: string, source: string): AnswerIndexEntry | null {
  if (!source.startsWith("---")) return null;
  const end = source.indexOf("\n---", 3);
  if (end === -1) return null;
  const block = source.slice(3, end);

  const get = (key: string): string | undefined => {
    const m = block.match(new RegExp(`^${key}:\\s*(.*)$`, "m"));
    return m ? m[1].trim() : undefined;
  };

  const rawQuestion = get("question");
  let question = rawQuestion ?? slug;
  if (rawQuestion?.startsWith('"')) {
    try {
      question = JSON.parse(rawQuestion) as string;
    } catch {
      question = rawQuestion;
    }
  }

  return {
    slug,
    question,
    strategy: get("strategy") ?? "markdown_kb",
    filed_at: get("filed_at") ?? "",
  };
}

/** Rebuild `wiki/answers/index.md` by scanning the answers directory. */
export function regenerateAnswersIndex(): void {
  fs.mkdirSync(WIKI_ANSWERS_DIR, { recursive: true });
  const files = fs
    .readdirSync(WIKI_ANSWERS_DIR)
    .filter((f) => f.toLowerCase().endsWith(".md") && f !== "index.md");

  const entries: AnswerIndexEntry[] = [];
  for (const file of files) {
    const slug = path.basename(file, ".md");
    const source = fs.readFileSync(path.join(WIKI_ANSWERS_DIR, file), "utf-8");
    const entry = parseAnswerFrontMatter(slug, source);
    if (entry) entries.push(entry);
  }

  fs.writeFileSync(WIKI_ANSWERS_INDEX_PATH, renderAnswersIndex(entries));
}

/** Write a reviewed answer to `wiki/answers/<slug>.md` and refresh the answers index. */
export function fileAnswer(input: FiledAnswerInput): { slug: string; file: string } {
  const slug = answerSlug(input.query);
  fs.mkdirSync(WIKI_ANSWERS_DIR, { recursive: true });
  fs.writeFileSync(path.join(WIKI_ANSWERS_DIR, `${slug}.md`), renderFiledAnswer(input));
  regenerateAnswersIndex();
  return { slug, file: `wiki/answers/${slug}.md` };
}
