import fs from "node:fs";
import {
  CONSOLIDATED_DOC_PATH,
  DREAM_DIR,
  DREAM_EMBED_CACHE_PATH,
  DREAM_STATE_PATH,
} from "../lib/paths.js";
import { OPENAI_EMBEDDING_MODEL } from "../env.js";
import { getOpenAI } from "../llm/client.js";
import { hashContent } from "../strategies/vector-rag/incremental.js";
import { answerSlug } from "../strategies/markdown-kb/answer-filing.js";
import { buildIndex } from "../strategies/markdown-kb/indexer.js";
import { buildVectorIndex } from "../strategies/vector-rag/indexer.js";
import { clusterByCosine, selectClusters } from "./cluster.js";
import { distillCluster, type QAPair } from "./distill.js";
import { readTurns } from "./log.js";

const COSINE_THRESHOLD = 0.85;
const MIN_OCCURRENCES = 3;
/** Cap distinct Q&A pairs fed to the distiller, to bound the prompt size. */
const MAX_DISTILL_PAIRS = 8;

interface ConsolidatedEntry {
  fingerprint: string;
  slug: string;
  question: string;
  answer: string;
  occurrences: number;
  promoted_at: string;
}

interface DreamState {
  entries: ConsolidatedEntry[];
}

export interface DreamPromotion {
  slug: string;
  question: string;
  occurrences: number;
}

export interface DreamReport {
  scanned: number;
  valid: number;
  clusters: number;
  promoted: DreamPromotion[];
  skipped: number;
  reindexed?: { sections: number; chunks: number };
}

function normalize(q: string): string {
  return q.trim().toLowerCase().replace(/\s+/g, " ");
}

/** Deterministic id for a cluster: hash of its sorted, distinct, normalized questions. */
function fingerprintOf(questions: string[]): string {
  const distinct = [...new Set(questions.map(normalize))].sort();
  return hashContent(distinct.join("\n"));
}

function loadState(): DreamState {
  if (!fs.existsSync(DREAM_STATE_PATH)) return { entries: [] };
  try {
    const parsed = JSON.parse(fs.readFileSync(DREAM_STATE_PATH, "utf-8")) as DreamState;
    return Array.isArray(parsed.entries) ? parsed : { entries: [] };
  } catch {
    return { entries: [] };
  }
}

function loadEmbedCache(): Record<string, number[]> {
  if (!fs.existsSync(DREAM_EMBED_CACHE_PATH)) return {};
  try {
    return JSON.parse(fs.readFileSync(DREAM_EMBED_CACHE_PATH, "utf-8")) as Record<string, number[]>;
  } catch {
    return {};
  }
}

/** Embed each question, reusing cached vectors (keyed by content hash) and
 *  batching the misses into a single embeddings call. */
async function embedQuestions(questions: string[]): Promise<number[][]> {
  const cache = loadEmbedCache();
  const misses = [...new Set(questions.map((q) => [hashContent(q), q] as const))].filter(
    ([h]) => !cache[h],
  );

  if (misses.length > 0) {
    const openai = getOpenAI();
    const res = await openai.embeddings.create({
      model: OPENAI_EMBEDDING_MODEL,
      input: misses.map(([, q]) => q),
    });
    misses.forEach(([h], i) => {
      cache[h] = res.data[i].embedding;
    });
    fs.mkdirSync(DREAM_DIR, { recursive: true });
    fs.writeFileSync(DREAM_EMBED_CACHE_PATH, JSON.stringify(cache));
  }

  return questions.map((q) => cache[hashContent(q)]);
}

function uniqueSlug(base: string, used: Set<string>): string {
  let slug = base;
  let n = 2;
  while (used.has(slug)) slug = `${base}-${n++}`;
  used.add(slug);
  return slug;
}

/** Render docs/_consolidated.md from the consolidated entries (newest first). */
function renderConsolidatedDoc(entries: ConsolidatedEntry[]): string {
  const header = [
    "---",
    "source_type: faq",
    "---",
    "",
    "<!-- Generated by POST /dream from repeatedly-asked, grounded answers. Do not edit by hand. -->",
  ];
  const sorted = [...entries].sort(
    (a, b) => b.promoted_at.localeCompare(a.promoted_at) || a.slug.localeCompare(b.slug),
  );
  const blocks = sorted.map((e) => `## ${e.question}\n\n${e.answer}`);
  return [...header, "", blocks.join("\n\n"), ""].join("\n");
}

/**
 * Run one consolidation pass: cluster repeatedly-asked, grounded questions,
 * distill each new cluster into a canonical FAQ entry, promote it into the
 * indexed KB, and rebuild the indexes. Idempotent — a re-run with no new
 * clusters promotes nothing and leaves the doc untouched.
 */
export async function runDream(now: string = new Date().toISOString()): Promise<DreamReport> {
  const turns = readTurns();
  const valid = turns.filter((t) => t.status === "VALID");

  const report: DreamReport = {
    scanned: turns.length,
    valid: valid.length,
    clusters: 0,
    promoted: [],
    skipped: 0,
  };
  console.log(`[dream] scanned ${turns.length} turns, ${valid.length} VALID`);
  if (valid.length < MIN_OCCURRENCES) return report;

  // One vector per VALID turn (duplicates hit the embed cache), so cluster size
  // equals the number of times the intent was asked.
  const vectors = await embedQuestions(valid.map((t) => t.query));
  const selected = selectClusters(clusterByCosine(vectors, COSINE_THRESHOLD), MIN_OCCURRENCES);
  report.clusters = selected.length;

  const state = loadState();
  const knownFingerprints = new Set(state.entries.map((e) => e.fingerprint));
  const usedSlugs = new Set(state.entries.map((e) => e.slug));
  const newEntries: ConsolidatedEntry[] = [];

  for (const group of selected) {
    const groupTurns = group.map((i) => valid[i]);
    const fingerprint = fingerprintOf(groupTurns.map((t) => t.query));
    if (knownFingerprints.has(fingerprint)) {
      report.skipped += 1; // already consolidated in a prior run
      continue;
    }

    // Distinct (question, answer) pairs — most-recent answer wins per question.
    const byQuestion = new Map<string, QAPair>();
    for (const t of groupTurns) byQuestion.set(normalize(t.query), { question: t.query, answer: t.answer });
    const pairs = [...byQuestion.values()].slice(0, MAX_DISTILL_PAIRS);

    const distilled = await distillCluster(pairs);
    if (!distilled) {
      report.skipped += 1; // fail-open: never write a half-baked entry
      continue;
    }

    const slug = uniqueSlug(answerSlug(distilled.question), usedSlugs);
    const entry: ConsolidatedEntry = {
      fingerprint,
      slug,
      question: distilled.question,
      answer: distilled.answer,
      occurrences: group.length,
      promoted_at: now,
    };
    newEntries.push(entry);
    knownFingerprints.add(fingerprint);
    report.promoted.push({ slug, question: distilled.question, occurrences: group.length });
  }

  if (newEntries.length === 0) return report; // nothing new → no writes, fully idempotent

  state.entries.push(...newEntries);
  fs.mkdirSync(DREAM_DIR, { recursive: true });
  fs.writeFileSync(DREAM_STATE_PATH, JSON.stringify(state, null, 2));
  fs.writeFileSync(CONSOLIDATED_DOC_PATH, renderConsolidatedDoc(state.entries));
  console.log(`[dream] promoted ${newEntries.length} entries → ${CONSOLIDATED_DOC_PATH}`);

  const md = buildIndex();
  const vec = await buildVectorIndex();
  report.reindexed = { sections: md.sections_indexed, chunks: vec.chunks_indexed };
  return report;
}
